import './global.css';
import type { Metadata, Viewport } from 'next';
import { AccessibilityProvider } from './context/AccessibilityContext';

export const metadata: Metadata = {
  title: '유나&희도 - Quiz',
  description: 'Generated by SMJ426',
  icons: {
    icon: '/images/favicon.png',
  },
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <div id="modal-root" />
        <AccessibilityProvider>{children}</AccessibilityProvider>
      </body>
    </html>
  );
}
