import type { Metadata, Viewport } from 'next';
import './global.css';

export const metadata: Metadata = {
  title: '유나&희도 - Quiz',
  description: 'Generated by SMJ426',
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>{children}</body>
    </html>
  );
}
